### PR TITLE
Overridable defaults

### PR DESCRIPTION
**Pull request by retr0h**
The defaults should be overridable.

### CODE REVIEW

**Comment by dguerri** [comment]
Hi @retr0h, thanks!
I am not fully convinced of this approach, tho. My initial idea was to have the relevant parameters (ideally all the available parameters) configured inside the roles. Default values would be the defaults used by each project, according to the official doc. Then, you can override defaults using role variables.
So if you need to add more parameters, it could be better to add those and set them to openstack default value in defaults/main.yml

**Comment by retr0h** [comment]
Hey @dguerri. IMO - the preferred approach to writing roles, is to provide all defaults in defaults.  They can then be overriden in host vars, group vars, inventory, or through parametrized roles.

I feel that the variabilization provides more flexibility.  People don't have to do it, but if they find they need to they can.

**Comment by dguerri** [comment]
I don't know. Need to think a bit about it.
Defaults are already in defaults: you can override all of them just using role variables. And, in general, i would prefer to be more explicit (defining as much attributes as possible with default values).
I can see your point (the added flexibility) and I agree that replacing the set of attributes would be optional. But replacing them with a subset would make the solution more dependent from the initial configuration provided by the packagers. I am also worried about "exposing" that level of detail as I think the role should be sure-easy to use.
Let's keep discussing, I am open to your solution.

**Comment by retr0h** [comment]
@dguerri Yeah, once you start changing attributes, you are on your own, and I would assume you know what you are doing.  I would tend to agree with that.  It also means you can break things in bad ways too.

I don't have a particular use case at the moment to override these values.  I personally liked the code organization better with them in defaults, and could see myself needing to override options down the road.

Let me put this PR on hold.  I'm just now starting to integrate against these roles against OSP5, then quickly to OSP7.  Probably see a lot more from me in the future.  Including running Keystone behind Apache or Nginx.

**Comment by dguerri** [comment]
That's brilliant!

**Pull request closed without merging**
