### PR TITLE
Use openstack-ansible modules

### PR DESCRIPTION
**Pull request by retr0h**
We should be using the community standard opentack modules.  These
are in progress of being migrated into core ansible.  We should
align ourselves with these, so we can cut over to upstream ansible
in the future.

https://github.com/openstack-ansible/openstack-ansible-modules

### CODE REVIEW

**Comment by dguerri** [comment]
Agreed. I wrote those quick and dirty modules to fill a gap we had in ansible core/ext.
I will test this PR as soon as possible. Meanwhile, if @abelboldu and/or @proffalken ""volunteer""... :D

**Comment by retr0h** [comment]
@dguerri any luck testing? My tests are passing on my side, but don't want to merge w/o your blessing.

**Comment by dguerri** [comment]
I will test it tomorrow morning first thing. BTW, are you sure that these are the official modules in Ansible 2.0? Afaik new openstack modules will use shade!

**Comment by retr0h** [comment]
My understanding is the [openstack ansible modules](https://github.com/openstack-ansible/openstack-ansible-modules), will be ported over to ansible as os_$module_name, as seen on [github](https://github.com/ansible/ansible-modules-core/tree/devel/cloud/openstack).  Yeah, they will use shade, and the port is a work in progress.  I simply wanted to align us now vs later.

Ideally we won't ship these modules with the roles any longer.

**Comment by dguerri** [comment]
I agree using the keystone_manage module, but I don't see the point in using the keystone_service as the service/endpoint modules are more similar to the ones that ansible will be using in 2.0 (I helped writing two of the candidates based on the code I used here, although it is not clear when they will be released)

**Comment by retr0h** [comment]
I don't see the `keystone_service/endpoint` modules anywhere.  Where are they?  Is there an outstanding PR?

**Comment by dguerri** [comment]
yeap... they are still in Monty's repo [here](https://github.com/emonty/ansible-modules-core/tree/feature/os_keystone) but they might not make it... I know Monty was working on a Keystone v3 version, but it is unclear if as a replacement or an integration for these.

**Comment by retr0h** [comment]
So, should we use the existing ones from my PR until something changes upstream?

**Comment by dguerri** [comment]
I think it makes sense for the manage module. But I am not sure about the other one as it is unlikely that there will be a single module for both services and endpoints: using the proposed one will make our code even more different from the one we will be using later!
But I guess the right question is: is there any reason why we should switch? (like features/fixes)

**Comment by retr0h** [comment]
My main, concern was using yet another set of modules, that are not maintained by anyone but yourself.  I was attempting to use a set of modules, that have been well established, tested, and used by many.  Truthfully, the openstack ansible modules, are the defacto modules.  This is why many of them are being merged into core.  If we are not using those, then we should be using what is in core ansible.  Since @emonty, has not gotten his modules into core ansible, I'm not sure why we wouldn't want to use the well established ones.

**Comment by dguerri** [comment]
Ok, I see your point now, thanks. But I would like to think about it a bit more. Would you please split this PR in 2 parts: one with the keystone manage and one with the existing modules replacement?

**Comment by retr0h** [comment]
Yeah, sure thats fine by me.

I was thinking about things like keystone v3.  We could implement that in your modules, however, that work really doesn't benefit the larger community b/c we are diverged from core ansible.  Since @emonty's work is not on the horizon anytime soon, I feel like we are carrying a bit of tech debt.

Where if we are running core module, we can fairly easily add v3 support locally, get the quick benefit, and in the background submit that work upstream for the larger community.

If @emonty's work was in already in openstack ansible modules, I would opt to just use that, but I don't see that happening anytime soon.

**Comment by dguerri** [comment]
If we get a reliable pointer to those modules I am 100% for importing them! :)

**Comment by retr0h** [comment]
Broke out keystone-manage into #10.

**Comment by dguerri** [comment]
Let's keep this "on hold" for a while.

**Pull request closed without merging**
